middleman = dependencies.detect { |dependency| dependency.name == 'middleman' }
raise 'Middleman dependency not found, please define before loading common gems.' if middleman.nil?
@middleman_major_version, @middleman_minor_version = middleman.requirement.to_s.scan(/\d+/).take(2).map(&:to_i)
if [@middleman_major_version, @middleman_minor_version].include?(nil) || ![3, 4].include?(@middleman_major_version)
  raise "Could not determine Middleman major and/or minor version, expected both to be present and major version 3 or 4 but got: major version: #{@middleman_major_version}, minor version: #{@middleman_minor_version}"
end

gem 'builder',                      '~> 3.2'
gem 'middleman-s3_sync',            @middleman_major_version == 3 ? '~> 3.3' : '~> 4.0'
gem 'middleman-cdn',                git: 'https://github.com/krautcomputing/middleman-cdn.git', branch: 'middleman4'
gem 'middleman-autoprefixer',       '~> 2.7'
gem 'middleman-bootstrap-navbar',   '~> 3.0'
gem 'middleman-blog',               @middleman_major_version == 3 ?
                                    { git: 'https://github.com/middleman/middleman-blog.git', branch: 'v3-stable' } : # TODO: Use >= 3.6 when released
                                    '~> 4.0'
gem 'middleman-livereload',         '~> 3.4'
gem 'middleman-sitemap-ping',       @middleman_major_version == 3 ? '~> 0.2' : '~> 1.0'
gem 'middleman-imageoptim',         '~> 0.2'
gem 'bootstrap-sass',               '~> 3.3', require: false
gem 'redcarpet',                    '~> 3.3'

if @middleman_major_version == 4
  gem 'middleman-sprockets',        '~> 4.1'
end
