# frozen_string_literal: true

middleman = dependencies.detect { |dependency| dependency.name == 'middleman' }
raise 'Middleman dependency not found, please define before loading common gems.' if middleman.nil?
@middleman_major_version, @middleman_minor_version = middleman.requirement.to_s.scan(/\d+/).take(2).map(&:to_i)
if [@middleman_major_version, @middleman_minor_version].include?(nil) || ![3, 4].include?(@middleman_major_version)
  raise "Could not determine Middleman major and/or minor version, expected both to be present and major version 3 or 4 but got: major version: #{@middleman_major_version}, minor version: #{@middleman_minor_version}"
end

gem 'bootstrap-sass',               '~> 3.3', require: false
gem 'middleman-autoprefixer',       '~> 2.7'
gem 'middleman-blog',               '~> 4.0'
gem 'middleman-bootstrap-navbar',   '~> 4.0'
gem 'middleman-cdn',                '~> 0.2'
gem 'middleman-imageoptim',         git: 'https://github.com/manuelmeurer/middleman-imageoptim.git', branch: 'improvements'
gem 'middleman-livereload',         '~> 3.4'
gem 'middleman-s3_sync',            '~> 4.0'
gem 'middleman-sitemap-ping',       '~> 1.0'
gem 'middleman-sprockets',          '~> 4.1'
gem 'redcarpet',                    '~> 3.3'
gem 'sass'                                 # Sass needs to be loaded before sass-globbing
gem 'sass-globbing',                '~> 1.1'
gem 'turbolinks',                   '~> 5.1', require: false
