gem 'builder',                      '~> 3.2'
gem 'middleman',                    '~> 3.3'
gem 'middleman-s3_sync',            '~> 3.0'
gem 'middleman-s3_redirect',        '~> 3.0'
gem 'middleman-cloudfront',         '~> 0.1'
gem 'middleman-cdn',                '~> 0.1'
gem 'middleman-autoprefixer',       '~> 2.3'
gem 'middleman-bootstrap-navbar',   '~> 2.0'
gem 'bootstrap-sass',               '~> 3.2', require: false
