group :development, :test do
  gem 'minitest-rails',             case @rails_major_version
                                    when 3 then '~> 1.0'
                                    when 4 then (@rails_minor_version == 0 ? '~> 1.0' : '~> 2.0')
                                    else        '~> 3.0'
                                    end
  gem 'minitest-reporters',         '~> 1.0'
  if @rails_major_version >= 4
    gem 'minitest-rails-capybara',  @rails_major_version == 4 ? { git: 'https://github.com/krautcomputing/minitest-rails-capybara.git', branch: '2.x_with_capybara_3' } : '~> 3.0'
  end
  gem 'minitest-focus',             '~> 1.1'
  gem 'minitest-around',            '~> 0.3'
end

group :development do
  gem 'guard-minitest',             '~> 2.4'
end
