# frozen_string_literal: true

{
  'sidekiq'          => ['~> 6.0'],
  'sidekiq-failures' => ['~> 1.0']
}.each do |gem_name, requirements_and_options|
  unless dependencies.any? { |dependency| dependency.name == gem_name }
    gem gem_name, *requirements_and_options
  end
end
