group :test do
  gem 'factory_girl_rails', '~> 4.4'
  gem 'ffaker',             '~> 2.0'
  gem 'capybara',           '~> 2.4'
  gem 'timecop',            '~> 0.7'
  gem 'database_rewinder',  '~> 0.2'
  gem 'vcr',                '~> 2.9'
  gem 'webmock',            '~> 3.0'
  gem 'simplecov',          '~> 0.9', require: false
  gem 'selenium-webdriver', '~> 3.6'
end
