# frozen_string_literal: true

group :test do
  {
    'capybara'          => ['~> 3.0'],
    'factory_bot_rails' => ['~> 5.0'],
    'ffaker'            => ['~> 2.0'],
    'webdrivers'        => ['~> 4.0']
  }.each do |gem_name, requirements_and_options|
    unless dependencies.any? { _1.name == gem_name }
      gem gem_name, *requirements_and_options
    end
  end
end
