# frozen_string_literal: true

group :development, :test do
  gem 'rspec-rails', '4.0.0.beta2' # TODO: Update to 4.x when released.
end

group :development do
  gem 'guard-rspec', '~> 4.2', require: false
end
