# frozen_string_literal: true

group :development, :test do
  {
    'rspec-rails' => ['~> 4.0']
  }.each do |gem_name, requirements_and_options|
    unless dependencies.any? { _1.name == gem_name }
      gem gem_name, *requirements_and_options
    end
  end
end

group :development do
  {
    'guard-rspec' => ['~> 4.2', require: false]
  }.each do |gem_name, requirements_and_options|
    unless dependencies.any? { _1.name == gem_name }
      gem gem_name, *requirements_and_options
    end
  end
end
