rails = dependencies.detect { |dependency| dependency.name == 'rails' }
raise 'Rails dependency not found, please define before loading common gems.' if rails.nil?
@rails_major_version, @rails_minor_version = rails.requirement.to_s.scan(/\d+/).take(2).map(&:to_i)
if [@rails_major_version, @rails_minor_version].include?(nil) || ![3, 4].include?(@rails_major_version)
  raise "Could not determine Rails major and/or minor version, expected both to be present and major version 3 or 4 but got: major version: #{@rails_major_version}, minor version: #{@rails_minor_version}"
end

# Basics
gem 'haml-rails',                     @rails_major_version == 3 ? '~> 0.4.0' : '~> 0.5'
gem 'sass-rails',                     @rails_major_version == 3 ? '~> 3.2'   : '~> 5.0'
gem 'coffee-rails',                   @rails_major_version == 3 ? '~> 3.2'   : '~> 4.0'
gem 'uglifier',                       '~> 2.5'
gem 'jquery-rails',                   '~> 3.1'

# Utils
gem 'pry',                            '~> 0.10', require: false
gem 'awesome_print',                  '~> 1.6',  require: false
gem 'nifty_settings',                 '~> 2.0'
gem 'newrelic_rpm',                   '~> 3.9'
gem 'tries',                          '~> 0.3'
gem 'rack-mini-profiler',             '~> 0.9', require: false
gem 'whenever',                       '~> 0.9', require: false
gem 'squeel',                         '~> 1.2'
gem 'autoprefixer-rails',             '~> 5.1'
gem 'rollbar',                        '~> 2.4'
gem 'fakeredis',                      '~> 0.5', require: false
gem 'premailer-rails',                '~> 1.8'
gem 'nokogiri',                       '~> 1.6'
gem 'has_defaults',                   '~> 0.4'
gem 'fetchy',                         '~> 0.1.0.alpha9', require: false # TODO: Upgrade to never version when released.
gem 'fast_blank',                     '~> 1.0'

# Services
gem 'services',                       '~> 4.1'

# Postgres
gem 'pg',                             '~> 0.18'
gem 'postgres_ext',                   @rails_major_version == 3 ? '~> 1.0' : '~> 2.3'

if @rails_major_version == 4 && @rails_minor_version > 1
  gem 'schema_plus_indexes',          '~> 0.2'
else
  gem 'schema_plus',                  '~> 1.8'
end

group :development, :test do
  gem 'pry-byebug',                   '~> 1.3' # Don't use never version, unless it works with with pry-remote:
                                               # https://github.com/deivid-rodriguez/pry-byebug/issues/33
end

group :development do
  gem 'bullet',                       '~> 4.12'
  gem 'letter_opener',                '~> 1.2'
  gem 'quiet_assets',                 '~> 1.0'
  gem 'annotate',                     '~> 2.6', require: false
  gem 'better_errors',                '~> 2.0'
  gem 'binding_of_caller',            '~> 0.7'
  gem 'pry-remote',                   '~> 0.1'
  gem 'derailed_benchmarks',          '~> 0.0'
  gem 'guard',                        '~> 2.12'
end

group :production do
  gem 'lograge',                      '~> 0.3'
  gem 'puma',                         '~> 2.8', require: false
end
