# frozen_string_literal: true

GIT_SOURCE_RAILS = 'https://github.com/rails/rails.git'
rails = dependencies.detect { |dependency| dependency.name == 'rails' }
raise 'Rails dependency not found, please define before loading common gems.' if rails.nil?
if rails.source.is_a?(Bundler::Source::Git)
  git_source, git_branch = rails.source.options.fetch_values('git', 'branch')
  unless git_source == GIT_SOURCE_RAILS
    raise "Expected Git source for Rails to be #{GIT_SOURCE_RAILS} but it's #{git_source}."
  end
  unless branch_match = git_branch.match(/\A(\d)-(\d)-stable\z/)
    raise "Expected Git branch for Rails to be of format x-y-stable but it's #{git_branch}."
  end
  @rails_major_version, @rails_minor_version = branch_match.captures.map(&:to_i)
else
  @rails_major_version, @rails_minor_version = rails.requirement.to_s.scan(/\d+/).take(2).map(&:to_i)
end
expected_rails_major_versions = 4..6
if [@rails_major_version, @rails_minor_version].include?(nil) || !expected_rails_major_versions.include?(@rails_major_version)
  raise "Could not determine Rails major and/or minor version, expected both to be present and major version to be one of #{expected_rails_major_versions.to_a} but got: major version: #{@rails_major_version}, minor version: #{@rails_minor_version}"
end

gem 'autoprefixer-rails',                   '~> 9.0'
gem 'awesome_print',                        '~> 1.6',  require: false
gem 'bootsnap',                             '~> 1.1',  require: false
gem 'fast_blank',                           '~> 1.0'
gem 'haml-rails',                           @rails_major_version == 5 && @rails_minor_version >= 1 ? '~> 2.0' : '~> 1.0'
gem 'has_defaults',                         '~> 0.4'
gem 'nokogiri',                             '~> 1.6'
gem 'oj',                                   '~> 3.0'
gem 'pg',                                   @rails_major_version == 4 ? '~> 0.20.0' : '~> 1.0' # v1.0 is not supported in Rails < 5 and v0.21 shows annoying deprecation warnings.
gem 'premailer-rails',                      '~> 1.8'
gem 'pry',                                  '~> 0.10', require: false
gem 'rack-attack',                          '~> 6.0'
gem 'rack-mini-profiler',                   '~> 1.0',  require: false
gem 'rollbar',                              '~> 2.4'
gem 'sassc-rails',                          '~> 2.0'
gem 'services',                             '~> 7.0'
gem 'strip_attributes',                     '~> 1.8',  require: false
gem 'tries',                                '~> 0.3'
gem 'turbolinks',                           '~> 5.0'
gem 'uglifier',                             '~> 4.1'
gem 'whenever',                             '~> 1.0',  require: false

case
when @rails_major_version == 4
  gem 'activerecord-collection_cache_key',  '~> 0.1'
  gem 'jquery-rails',                       '~> 4.1'
  gem 'postgres_ext',                       '~> 3.0'

  if @rails_minor_version == 2
    gem 'where-or',                         '~> 0.1'
  end
when @rails_major_version >= 5
  gem 'active_record_extended',             '~> 1.0'
  gem 'webpacker',                          '~> 4.0'
end

group :development, :test do
  gem 'byebug',                             '~> 9.0'
end

group :development do
  gem 'annotate',                           '~> 2.6', require: false
  gem 'better_errors',                      '~> 2.0'
  gem 'binding_of_caller',                  '~> 0.7'
  gem 'bullet',                             '~> 5.0'
  gem 'derailed_benchmarks',                '~> 1.3'
  gem 'guard',                              '~> 2.12'
  gem 'letter_opener',                      '~> 1.2'
  gem 'marginalia',                         '~> 1.4'
  gem 'pry-remote',                         '~> 0.1'

  if @rails_major_version == 4
    gem 'quiet_assets',                     '~> 1.0'
  end
end

group :production do
  gem 'lograge',                            '~> 0.3'
  gem 'puma',                               '~> 4.0', require: false
end
