GIT_SOURCE_RAILS = 'https://github.com/rails/rails.git'
rails = dependencies.detect { |dependency| dependency.name == 'rails' }
raise 'Rails dependency not found, please define before loading common gems.' if rails.nil?
if rails.source.is_a?(Bundler::Source::Git)
  git_source, git_branch = rails.source.options.fetch_values('git', 'branch')
  unless git_source == GIT_SOURCE_RAILS
    fail "Expected Git source for Rails to be #{GIT_SOURCE_RAILS} but it's #{git_source}."
  end
  unless branch_match = git_branch.match(/\A(\d)-(\d)-stable\z/)
    fail "Expected Git branch for Rails to be of format x-y-stable but it's #{git_branch}."
  end
  @rails_major_version, @rails_minor_version = branch_match.captures.map(&:to_i)
else
  @rails_major_version, @rails_minor_version = rails.requirement.to_s.scan(/\d+/).take(2).map(&:to_i)
end
expected_rails_major_versions = 3..5
if [@rails_major_version, @rails_minor_version].include?(nil) || !expected_rails_major_versions.include?(@rails_major_version)
  raise "Could not determine Rails major and/or minor version, expected both to be present and major version to be one of #{expected_rails_major_versions.to_a} but got: major version: #{@rails_major_version}, minor version: #{@rails_minor_version}"
end

# Basics
gem 'haml-rails',                           @rails_major_version == 3 ? '~> 0.4.0' : '~> 1.0'
gem 'sass-rails',                           @rails_major_version == 3 ? '~> 3.2' : '~> 5.0'
gem 'coffee-rails',                         @rails_major_version == 3 ? '~> 3.2' : '~> 4.0'
gem 'uglifier',                             '~> 2.5'
gem 'jquery-rails',                         @rails_major_version > 4 || (@rails_major_version == 4 && @rails_minor_version >= 2) ? '~> 4.1' : '~> 3.1'

# Utils
gem 'pry',                                  '~> 0.10', require: false
gem 'awesome_print',                        '~> 1.6',  require: false
gem 'nifty_settings',                       '~> 2.0'
gem 'newrelic_rpm',                         '~> 3.9'
gem 'tries',                                '~> 0.3'
gem 'rack-mini-profiler',                   '~> 0.9', require: false
gem 'whenever',                             '~> 0.9', require: false
gem 'autoprefixer-rails',                   '~> 7.0'
gem 'rollbar',                              '~> 2.4'
gem 'fakeredis',                            '~> 0.5', require: false
gem 'premailer-rails',                      '~> 1.8'
gem 'nokogiri',                             '~> 1.6'
gem 'has_defaults',                         '~> 0.4'
gem 'fetchy',                               '~> 0.1', require: false
gem 'fast_blank',                           '~> 1.0'
gem 'oj',                                   '~> 3.0'

# Services
gem 'services',                             @rails_major_version == 3 ? '~> 4.1.4' : '~> 5.0'

# Postgres
gem 'pg',                                   @rails_major_version <= 4 ? '~> 0.20.0' : '~> 0.21' # v0.21 shows annoying deprecation warnings in Rails <= 4

if @rails_major_version <= 4
  gem 'postgres_ext',                       @rails_major_version == 3 ? '~> 1.0' : '~> 3.0'
  gem 'activerecord-collection_cache_key',  '~> 0.1'
end

if @rails_major_version == 4 && @rails_minor_version == 2
  gem 'where-or',                           '~> 0.1'
end

if (@rails_major_version == 4 && @rails_minor_version <= 1) || (@rails_major_version == 3 && @rails_minor_version >= 2)
  gem 'schema_plus',                        '~> 1.8'
elsif @rails_major_version == 4 && @rails_minor_version > 1
  gem 'schema_plus_indexes',                '~> 0.2'
end

group :development, :test do
  gem 'byebug',                             '~> 9.0'
end

group :development do
  gem 'letter_opener',                      '~> 1.2'
  gem 'annotate',                           '~> 2.6', require: false
  gem 'better_errors',                      '~> 2.0'
  gem 'binding_of_caller',                  '~> 0.7'
  gem 'pry-remote',                         '~> 0.1'
  gem 'derailed_benchmarks',                '~> 0.0'
  gem 'guard',                              '~> 2.12'
  gem 'marginalia',                         '~> 1.4'

  if @rails_major_version < 5
    gem 'quiet_assets',                     '~> 1.0'
  end

  if @rails_major_version >= 4
    gem 'bullet',                           '~> 5.0'
  end
end

group :production do
  gem 'lograge',                            '~> 0.3'
  gem 'puma',                               '~> 3.1', require: false
end
